### ISSUE TITLE
Secret Key shouldn't be in a browser

### ISSUE THREAD

**Issue by danschumann** [nimbis/s3commander#11]

**Comment by CtrlC-Root** [comment]
@danschumann Do you have any advice on how this could be written to avoid that? Or are you suggesting that the entire concept of a client-side S3 browser is bad?

We need the secret key to sign requests to AWS so I'm not sure if there's a way to avoid storing it in memory in the browser.

**Comment by electroniceagle** [comment]
I believe we can create temporary tokens with STS.
http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/prog-services-sts.html

**Comment by CtrlC-Root** [comment]
@electroniceagle Neat! I suppose if someone wants this functionality and were willing to add it I think it would be a good addition.

**Comment by CtrlC-Root** [comment]
Something I just thought about now is this would probably prevent s3commander from being usable with alternative S3 implementations (such as the Ceph RADOS gateway). It should be implemented so it's either optional or a different backend altogether.

**Comment by CtrlC-Root** [comment]
The rewrite that's currently in progress has support for using temporary credentials as provided by STS. We could even take another step in that direction and modify the `S3Session` component to generate temporary credentials if the user supplies real IAM credentials without a session token.

**Comment by CtrlC-Root** [comment]
Given we now support STS credentials I'm closing this issue. Take a look at the parameters to the `S3Session` component for more details.
