### ISSUE TITLE
NetworkingError: Network Failure

### ISSUE THREAD

**Issue by mint5auce** [nimbis/s3commander#15]
Running S3Commander locally, I get the above error when trying to connect to my bucket.

I can successfully connect with the same details using other methods (such as transmit.app). I am using the 's3-eu-west-2' region.

What is causing the error? Can I get any more detailed feedback?

Thanks!

**Comment by CtrlC-Root** [comment]
That doesn't seem like a valid region to me. Can you try using the `eu-west-2` region instead? Check out [the AWS documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for a complete list of regions. Does that fix it?

**Comment by ahaurat** [comment]
Having the same issue. I'm using 'us-west-1' so I'm guessing this issue isn't actually related to the region.

**Comment by CtrlC-Root** [comment]
@ahaurat Are you using the latest release or `master`? The latest release only works for the older AWS signing protocol (v2) and therefore in regions like GovCloud. We're in the middle of a rewrite which supports the newer signing protocol (v4) which should fix this issue. That's why I haven't closed it yet, I'm waiting for the next release.

**Comment by ahaurat** [comment]
@CtrlC-Root using `master` branch

![screen shot 2018-05-31 at 9 40 21 am](https://user-images.githubusercontent.com/3485980/40795410-db4df4a0-64b6-11e8-8146-f30b99afe1f8.png)

**Comment by CtrlC-Root** [comment]
@ahaurat I see you're running this locally. Did you configure a CORS policy on the S3 bucket that would allow that? I use the following for testing purposes:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Comment by ahaurat** [comment]
@CtrlC-Root Thanks for that! I had * for AllowedOrigin and thought that was enough but apparently I also needed the * for AllowedHeader. Cheers!

**Comment by CtrlC-Root** [comment]
@ahaurat So it works? Obviously, once you host this in production somewhere, you'll want to restrict the CORS policy for security.

**Comment by ahaurat** [comment]
Yup, it works great. Will definitely restrict the policy for production. Thanks again!

**Comment by CtrlC-Root** [comment]
Glad to hear. I'm going to close this issue for now. When we reach feature parity with our previous implementation we'll make another stable release. Until then, feel free to open another issue or make a pull request if you run into anything serious.

**Comment by blake-regalia** [comment]
I think this bit about the CORS configuration for localhost development would make a nice addition to the README!

**Comment by CtrlC-Root** [comment]
You're right, I'm going to add it right now.
