### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by pbllms** [nimbis/s3commander#8]
All of the syntax,
`
      return (
        <div className={this.props.style.control}>
          <span>Show Deleted Files</span>
          <input
            type="checkbox"
            id="chkShowDeleted"
            defaultChecked={this.props.options.showDeletedFiles ? "checked" : ""} />
        </div>
      );
`

for example gives javascript compile errors about Uncaught SyntaxError: Unexpected token < using Google Chrome Browser but used others as well with same issue.

**Comment by CtrlC-Root** [comment]
@pbllms The README.md should probably be updated but you need to either include the JSX in-browser transformer (take a look at `JSXTransformer-0.12.2.js` in the example `index.html` file) or run the JavaScript source through the JSX preprocessor before using it.

**Comment by electroniceagle** [comment]
@CtrlC-Root just gave you write access in case you get bored and want to tinker

**Comment by pbllms** [comment]
Yes, we saw that but are using HTTPS and it causes issues with mixed content so we use this location instead,  

https://cdnjs.cloudflare.com/ajax/libs/react/0.12.2/JSXTransformer.js

And we still get the same issues including it and react.js before s3commander.js

Also see this https://facebook.github.io/react/jsx-compiler.html

I also downloaded and ran in Xampp locally to test and it doesn't work for me there either using your repo/example and all it's code.  I get Uncaught SyntaxError: Unexpected end of input http://dragon.ak.fbcdn.net/hphotos-ak-xpa1/t39.3284-6/10541015_309770302547476_509859315_n.js

**Comment by CtrlC-Root** [comment]
@electroniceagle Thanks. It looks like I'm going to be using s3commander at my current job so I'll probably be opening pull requests for new features here and there.

@pbllms I just checked out the contents of the master branch, made it available through S3 static hosting, and loaded the `index.html` file. It seems to work out of the box for me in Google Chrome. I must be missing something about your situation because it should be working.

**Comment by CtrlC-Root** [comment]
@pbllms I'm going to close this issue. If you're still experiencing a problem feel free to comment here or open another issue.
